### ISSUE TITLE
There are missing the following Bee´s Palette icons: Soundscape and 1X2 Debris (A) and (B) - (v0.4.5)

### ISSUE THREAD

**Issue by LautaroL20** [koerismo/QOL-BEE#16] opened 2020-06-14 03:24 UTC
![1X2 Debris (A) and (B) are missing their icons in the Bee´s Palette](https://user-images.githubusercontent.com/12244376/84583914-1b8baf80-add5-11ea-95e7-289ca1aa176c.png)

![Soundscape is missing its icon in both the In-Game Palette and Bee´s Palette](https://user-images.githubusercontent.com/12244376/84583915-1dee0980-add5-11ea-8dea-a0ed269442de.png)

**Comment by koerismo** [comment] 2020-06-14 04:09
This is a duplicate of #15 . I just have to make the icon and then I can implement it both ingame and in bee.

**Closed by koerismo** 2020-06-14 04:09 UTC
Labels: bug
